### ISSUE TITLE
Export pbs ? Can not see `with-stubs` nor `nth-mock-args-for` and others

### ISSUE THREAD

**Issue by vindarel** [Chream/cl-mock#1]
Hi,
Nice to find this lib :) I added it on Cliki.

I installed it with quicklisp (`ql:quickload :cl-mock)`) and tried to use it but I can't find all functions: 

- `(cl-mock:nth TAB` => nothing
- `(cl-mock::nth TAB` => (with double colons) `nth-value-for`, `nth-value`, `nthcdr`
- I can't find `with-stubs`. `(cl-mock:with-` => with-mocks only, `(cl-mock::with-` => many more but no "with-stubs" nor `with-dynamic-`; can not find `verify-*`,…

so it looks like there is a pb with exported stuff (note that I have `with-mocks`). Also your use of `uiop:define-package` instead of `asdf` seems unusual to me but I can't judge.

**Comment by Chream** [comment]
Hi, sorry but I think you might be at the wrong repository? This is not the cl-mock that is on quicklisp. I made this before knowing that there already was a cl-mock library. Going to change the name and make an update soon though.

**Comment by vindarel** [comment]
OMG you are right, sorry^^ I was indeed trying out https://github.com/Ferada/cl-mock I'll try both when I can and come back with any more remark :) Regards.

(thanks for the QL tip, I was wondering)
